version: "3"

services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: error
    ports:
      - "27017:27017"
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: error
      ME_CONFIG_MONGODB_URL: mongodb://admin:error@mongo:27017/
    ports:
      - "8081:8081"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://admin:error@mongo:27017/
    ports:
      - "5050:5050"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
